### ISSUE TITLE
d1s3 Bonus: given test set, compute confidence intervals

### ISSUE THREAD

**Issue by Goschjann** [compstat-lmu/lecture_i2ml#101]
maybe for next year, maybe in exercise

**Comment by berndbischl** [comment]
@giuseppec please do this in cim2

**Comment by berndbischl** [comment]
tranfser the issue and close it here please, also look at the PR

**Comment by giuseppec** [comment]
Für das Nonparametric Confidence Interval fand ich das Material hier besser: https://sebastianraschka.com/blog/2016/model-evaluation-selection-part2.html#the-bootstrap-method-and-empirical-confidence-intervals

**Comment by berndbischl** [comment]
in cim2 now closing here
