### ISSUE TITLE
Create graphic from photo

### ISSUE THREAD

**Issue by christophM** [compstat-lmu/lecture_i2ml#196]
Please turn the following overview in the photo into a graphic that we can use in the slides:

![2018-03-08 09 55 24](https://user-images.githubusercontent.com/1632100/37329081-a33a846e-269c-11e8-9c1b-b226d49ed5fd.jpg)

**Comment by fabian-s** [comment]
DanielSchalk says: obacht, visualization must show clearly that this is being done repeatedly many times.
Bernd says: should be an animation.

**Comment by berndbischl** [comment]
a agree we should create a better animatio for nested resampling

**Comment by RifatMehreen** [comment]
I have used draw.io for the graphic. The link: https://drive.google.com/file/d/1xjBfaPx5JDvjGt0p6E7Q-AGsrALLKcVC/view?usp=sharing

**Comment by RifatMehreen** [comment]
The figures are attached here:
part1: 
![outer_CV](https://user-images.githubusercontent.com/21968577/61883081-0b878a80-aefa-11e9-9532-ad512e7a1c1d.png)

part2:
![outer_CV_2](https://user-images.githubusercontent.com/21968577/61883153-2ce87680-aefa-11e9-87c6-e05b083e84bc.png)

part3:
![outer_CV_3](https://user-images.githubusercontent.com/21968577/61883184-3bcf2900-aefa-11e9-8260-f254ab8f4898.png)

**Comment by HeidiSeibold** [comment]
Can we close this?

**Comment by fabian-s** [comment]
... not yet.....
