### ISSUE TITLE
Exercise day 1, L1: Improve the proof

### ISSUE THREAD

**Issue by christophM** [compstat-lmu/lecture_i2ml#197]
The proove showing that the median optimizes a constant model, when using L1 is not complete: 
We also have to proove that at the n non-differentiable points, there is no optimum. 

Or alternatively use another way for prooving the exercise. For example there is a proof using induction.

**Comment by berndbischl** [comment]
@tpielok please remove the execrcse, we will proof this in CIM2

**Comment by berndbischl** [comment]
also one does NOT need induction the proof is much simpler...
