### ISSUE TITLE
wir wollen mindestens konstante baseline modelle mal definieren.

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#206]
also mittelwert oder median, und geschätzte probs bei classif.

beweise dass sowas optimal ist, kommen dann in cim2

**Comment by berndbischl** [comment]
eigentlich wollen wir das nicht, wir wollen das eher sehr "einfach" als baseline modelle in der evaluation besprecvhen

**Comment by berndbischl** [comment]
wir sollten nix beweisen, es sollte wirklich nur in der evaluation mal kurz erwähnt werden

**Comment by HeidiSeibold** [comment]
We have an exercise on this. Closing
