### ISSUE TITLE
maybe we short not seprate single exercises and the sheet?

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#219]
this seems to be overly complicated? 
i mean it its ok to have a single file, per exercise and solution, as this might be a longer file, but we dont need 2 separate folders? at the moment we have "exercises" for the sheets and "single_exercises"

**Comment by fabian-s** [comment]
1. having exercises in separate files is good : easy to diff, easier to vary exercises from year to year
2. Daniel already did a resonable structure for day 2 (a subfolder exercises for each day), let's do the rest the same way

**Comment by berndbischl** [comment]
ok fine

**Comment by HeidiSeibold** [comment]
Seems like this can be closed @berndbischl @fabian-s
