### ISSUE TITLE
Copyright pictures

### ISSUE THREAD

**Issue by KatyFisch** [compstat-lmu/lecture_i2ml#235]

**Comment by fabian-s** [comment]
probably not up-to-date. redo & chck, please @KatyFisch

**Comment by KatyFisch** [comment]
find . -name '*.Rnw' | ack -x 'figure_man/'
./03-performance/slides-roc-1.Rnw
73:\includegraphics[width=0.8\textwidth, height=4cm]{figure_man/roc-confmatrix1.png}
80:\includegraphics[width=0.8\textwidth, height=4cm]{figure_man/roc-confmatrix2.png}
93:  \includegraphics[width=\textwidth, height=7cm]{figure_man/roc-confmatrix-example.png}
103:\includegraphics[width=0.95\textwidth]{figure_man/roc-confmatrix-allterms.png}

./03-performance/roc-extra-unused.Rnw
32:% \includegraphics[width=0.75\textwidth]{figure_man/roc-curve-ex2.png}
48:% \includegraphics[width=0.8\textwidth]{figure_man/roc-mannwhitney3.png}
56:% \includegraphics[width=0.5\textwidth]{figure_man/roc-mannwhitney2.png}
70:% \includegraphics[width=0.5\textwidth]{figure_man/roc-mannwhitney2.png}

./03-performance/slides-roc-2.Rnw
13:% \includegraphics[width=0.7\textwidth, height=5.0cm]{figure_man/roc-space1.png}
124:\includegraphics[height=3.5cm,page=2]{figure_man/confusion_matrix_measures}
143:% \includegraphics[width=\textwidth]{figure_man/roc-curves2.png}
300:\includegraphics[width=0.8\textwidth,page=1]{figure_man/auc_interpretation.pdf}

./03-performance/slides-train-test.Rnw
17:\includegraphics[width=\textwidth, height=6cm,page=4]{figure_man/train_error.png}
106:\includegraphics[height=5.5cm]{figure_man/test_error.png}

./03-performance/perf_extra_stuff_unused.Rnw
79:    \includegraphics[width=7cm]{figure_man/bias_variance.png}

./03-performance/slides-resampling.Rnw
29:\includegraphics[width=5.5cm]{figure_man/ml_abstraction-crop.pdf}
47:\includegraphics[width=8cm]{figure_man/crossvalidation.png}

./01-intro/slides-tasks.Rnw
71:  \includegraphics[width=\textwidth]{figure_man/salary_prediction.png}
118:  \includegraphics[width=0.72\textwidth]{figure_man/lie-detector-polygraph.jpg}
161:  \includegraphics[width=0.8\textwidth]{figure_man/webmd.png}
234:  \includegraphics[height=0.5\textheight]{figure_man/ml-types.png}

./01-intro/slides-knn.Rnw
26:%  \includegraphics[width=.5\textwidth]{figure_man/nn.png}

./01-intro/slides-loss.Rnw
88:source("figure_man/plot_loss.R")

./01-intro/slides-limo.Rnw
116:source("figure_man/sse_lm_viz.R")
129:source("figure_man/sse_lm_viz.R")
142:source("figure_man/sse_lm_viz.R")
154:source("figure_man/sse_lm_viz.R")
163:source("figure_man/sse_lm_viz.R")
172:source("figure_man/sse_lm_viz.R")
181:source("figure_man/sse_lm_viz.R")
216:source("figure_man/sse_lm_viz.R")
226:{\centering \includegraphics{figure_man/l2-vs-l1-1.pdf}}
234:{\centering \includegraphics{figure_man/l2-vs-l1-2.pdf}}

./01-intro/slides-intro.Rnw
24:      \includegraphics[width=\textwidth]{figure_man/gears.png}
47:% \begin{center}\includegraphics[width=0.95\textwidth]{figure_man/learning} \end{center}
137:\begin{center}\includegraphics[width=0.8\textwidth]{figure_man/data_table} \end{center}
166:\begin{center}\includegraphics[width=0.9\textwidth]{figure_man/new_data0_web} \end{center}
182:\begin{center}\includegraphics[width=0.9\textwidth]{figure_man/new_data1_web} \end{center}
237:\begin{center}\includegraphics[width=\textwidth]{figure_man/what_is_a_model_web} \end{center}
293:\begin{center}\includegraphics[width=0.9\textwidth]{figure_man/the_model_web} \end{center}
312:\begin{center}\includegraphics[width=0.7\textwidth]{figure_man/the_inducer_web} \end{center}
328:\begin{center}\includegraphics[width=0.8\textwidth]{figure_man/eval_inducer1_web} \end{center}

./02-classification/slides-logistic.Rnw
693:%  \includegraphics{figure_man/mutualinformation.pdf}

./02-classification/slides-cultures.Rnw
189:      \node[below=of natur, label=below:algorithm] (algo) {\includegraphics[width = 3cm]{figure_man/machine.png}};

./02-classification/slides-classification.Rnw
47:{\centering \includegraphics[height = .7\textheight, width = .8\textwidth]{figure_man/classifier.pdf}}

./04-trees/slides-forests2.Rnw
95:\includegraphics[width = 10.3cm]{figure_man/rF_varImp_permutation.png}
190:  \begin{center}\includegraphics[width=0.95\textwidth]{figure_man/bm_stable_vs_unstable.pdf}\end{center}{}

./04-trees/slides-forests1.Rnw
39:\includegraphics[width=0.45\textwidth]{figure_man/bootstrapping.png}
53:\includegraphics[width=0.7\textwidth]{figure_man/rf_majvot_averaging.png}
155:\includegraphics[width=0.55\textwidth]{figure_man/forest.png}
287:\includegraphics[width=0.65\textwidth]{figure_man/rF_oob_error.png}

./04-trees/slides-cart2.Rnw
38:\includegraphics[width = \textwidth]{figure_man/monotone_trafo1.png}
48:\includegraphics[width = \textwidth]{figure_man/monotone_trafo2.png}

./04-trees/slides-cart1.Rnw
48:      \includegraphics[height = 5.0cm]{figure_man/labelling_of_tree.png}
61:      \includegraphics[height = 5.0cm]{figure_man/labelling_of_tree.png}
143:\includegraphics[height = 0.55\textheight]{figure_man/regression_tree}

./attic/slides-tasks.Rnw
26:\includegraphics[width=0.98\textwidth]{figure_man/food.png}

./05-tuning-nested/slides-tuning.Rnw
96:  \includegraphics[trim={0cm 0cm 0cm 0cm}, clip, width=1.2\textwidth]{figure_man/chain.jpg}
98:\includegraphics[trim={1cm 0cm 1cm 0cm}, clip, width=1.2\textwidth]{figure_man/tuning_process.jpg}

./05-tuning-nested/slides-nested-resampling.Rnw
139:\includegraphics[width=0.75\textwidth]{figure_man/autotune_in_model_fit.jpg}
152:\includegraphics[height=5.5cm]{figure_man/train_valid_test.jpg}
161:\includegraphics[width=8cm]{figure_man/train_valid_test.jpg}
163:\includegraphics[width=6cm]{figure_man/autotune_in_model_fit.jpg}
170:\begin{center}\includegraphics[height=5.5cm]{figure_man/Nested_Resampling.png}\end{center}
176:\begin{center}\includegraphics[height=5.5cm]{figure_man/Nested_Resampling.png}\end{center}
186:\begin{center}\includegraphics[height=5.5cm]{figure_man/Nested_Resampling.png}\end{center}
197:\begin{center}\includegraphics[height=5.5cm]{figure_man/Nested_Resampling.png}\end{center}
203:\begin{center}\includegraphics[height=5.5cm]{figure_man/Nested_Resampling.png}\end{center}

./code-demos/code_demo_4.Rnw
124:\includegraphics[height = 7.2cm, keepaspectratio]{figure_man/bm_stable_vs_unstable.jpg}

**Comment by KatyFisch** [comment]
Here the new one, but it's really just the code from the first line...
Also this is not supposed to be a list of all pictures that need copyright but more of a list that gets you an idea of how many pictures that might be

**Comment by HeidiSeibold** [comment]
What are the TODOs here?
