### ISSUE TITLE
PracticalAI github repo: beginner&intermediate level ml notebooks

### ISSUE THREAD

**Issue by c3m0zturk** [compstat-lmu/lecture_i2ml#237]
might be some valuable material for us? 
https://github.com/GokuMohandas/practicalAI

**Comment by fabian-s** [comment]
@tpielok  see whether/what we can use here & come talk to me then, please

**Comment by berndbischl** [comment]
and link this in a "internal collection list" like in cim2
maybe in the github wiki and link that from the README 
but we dont really need the issue here i guess

**Comment by berndbischl** [comment]
we shouldnt open issues for this, this is not concrete enough and will simply crowd the tracker for years. rather we should put this stuff into a well maintained list of "other matrial" we might want to review, in the readme or wiki

**Comment by HeidiSeibold** [comment]
Moved to wiki https://github.com/compstat-lmu/lecture_i2ml/wiki
