### ISSUE TITLE
we serioulsly need devel instuctions NOW

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#261]

**Comment by tpielok** [comment]
We have now a [devel branch](https://github.com/compstat-lmu/lecture_i2ml/tree/devel). There is at the moment a placeholder, where the devel instructions can be inserted.

**Comment by HeidiSeibold** [comment]
See issue #385 and pull request #402 

I moved all the things that we need to #385. Can we close this @berndbischl?

**Comment by fabian-s** [comment]
I think we can.....
