### ISSUE TITLE
dinge wie nummern und eine komplette liste der autoren namen müssen aus den slides rauis

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#262]

**Comment by berndbischl** [comment]
sowas gehört auf die webseite, oder gar nicht rein.
grund: es eschwert das partielle update später.

kommt ein autor dazu oder wollen wir ein chapter zwischenschieben wird alles entweder inkonsitent oder wir müssen alles neu dsrehen

**Comment by berndbischl** [comment]
genau definieren was auf die startseite kommt und was in den footer.

am besten 
- keine nummern
- copyright: Bischl et al, genauere personen auf webseite
- folienummern sind halt nur auf den teil bezogen.
- unten rechts: i2ml / chaper kürzel

**Comment by schalkdaniel** [comment]
hat sich das erledigt?

**Comment by berndbischl** [comment]
nein nicht ganz

**Comment by HeidiSeibold** [comment]
What is still missing here?

See also #389

**Comment by berndbischl** [comment]
> What is still missing here?

i just checked an arbitrary slideset from ml-basics from the refactoring branch. seems fine now IF we remove the department name and logo. and thats the other linked isse from above?

**Comment by HeidiSeibold** [comment]
> seems fine now IF we remove the department name and logo. and thats the other linked isse from above?

Exactly
