### ISSUE TITLE
macros NICHT ALLE in der preamble laden 

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#263]
das sollte lokal da geladen werden WO MAN ES BRAUCHT 

das steht abwer in der preamble

```
#% Defnes macros and environments
\input{../style/common.tex}
\input{../latex-math/basic-math.tex}
\input{../latex-math/basic-ml.tex}
\input{../latex-math/ml-bagging.tex}
\input{../latex-math/ml-boosting.tex}
\input{../latex-math/ml-trees.tex}
%\newcommand{\pikN}{\hat{\pi}^\Np}
```

**Comment by HeidiSeibold** [comment]
Hasn't this been fixed already? Can we close?

**Comment by fabian-s** [comment]
https://github.com/compstat-lmu/lecture_i2ml/blob/a50f5bb56249671247d4a8109f0f84ec9e1f11fd/style/preamble.Rnw#L52-L59

nope.

**Comment by berndbischl** [comment]
and this is a super-bad setup which just invites trouble down the line

**Comment by fabian-s** [comment]
why though...? what's so bad about loading all of latex-math?

**Comment by berndbischl** [comment]
> why though...? what's so bad about loading all of latex-math?

- macro clashes. yes, we should avoid them. but as you know, shit can happen
- debugging. if everything is loaded, that becomes mich harder

see it like this. each subchapter / file is basically an independent piece (of code and latex).
whats good (IMHO and i would say usually):
- cleanly state your INDIVIDUAL MINIMAL dependecies for each piece, in its header
what do we do:
- globally include everything

we might we fine now, and maybe there is no drastic risk now, but why not have a proper setup from the start?

**Comment by berndbischl** [comment]
we can also agree to stay with what we currently have, maybe there is more pressing issues. but i think what i am saying is kinda the cleaner approach

**Comment by berndbischl** [comment]
but please never at stuff like this
%\newcommand{\pikN}{\hat{\pi}^\Np}
directly into the preamble (uncommented)

**Comment by HeidiSeibold** [comment]
So should we then tag this as `next year` instead of `important`?

**Comment by berndbischl** [comment]
Let's, just do this at the end of this year. Things that take 10 min we should do immediately
