### ISSUE TITLE
ROC tables sometimes transposed

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#268]
this is a VERY MINOR issue. i didnt change this because i didnt want to redraw every thing

in conf matrices and ROC tables we sometimes put "predicted" in rows, and "true labels" in cols, and sometimes vice versa. 

we should check whether there is a simple way to have this consistent

**Comment by HeidiSeibold** [comment]
Should be consistent now. At least in slides.
