### ISSUE TITLE
ROC section could be made even more detailed, have a look at joaquins stuff

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#269]
this contains some nice extra details

https://joaquinvanschoren.github.io/ML-course

---> advanced model selection contains his ROC stuff

**Comment by berndbischl** [comment]
i removed some stuff into a file
roc-extra-unused.Rnw

that is somwhat old, and outdated
but there is also some potentially good stuff in there

should be reviewed for a potential extra lecture material, maybe we also need separate issues for this

**Comment by HeidiSeibold** [comment]
I think this is too much for our course (3ECTS).
