### ISSUE TITLE
empriical risk definition is inconsistent

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#274]
@fabian-s 

in the chapter on loss, we define the the emp risk as the AVERAGE loss over data.
later on, in the chater on LM we use the SUMMED loss. 

yes, this is no biggie, as for minimiation both are equivalent, but for what i am currently doing with the trees i at least need to know what our definition is (with sums its a bit easier)

anyway, point of this issue is: we should have ONE consistent definition.
my gut feeling says the sum is easier.

**Comment by schalkdaniel** [comment]
Lets have R and R bar

**Comment by fabian-s** [comment]
im fine with just using the sum. let's not introduce more notation unless we can help it.

**Comment by berndbischl** [comment]
> im fine with just using the sum. let's not introduce more notation unless it cannot be avoided

naja wir hatten die gleiche diskussion schon mal, da haben wir gesagt, lass nur den mittelwertnehmen. das hat dann hinten ein problem erzeugt, bei den trees bei mir. 
es ist wirklich strategisch besser R_bar zu haben, und R.
in 90% der fälle nehmen wir R.

SOLLTEN wir aber R_bar mal brauchen ist es da. OK?

**Comment by fabian-s** [comment]
this is no longer a problem, we now consistently use the average loss for the empirical risk in the tree chapters as well.
