### ISSUE TITLE
Tree example instability

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#278]
i have removed the tree example that demonstrates instability

a) because of issue #277 

b) because the example doesnt really work anymore if i encode the data correctly

**Comment by fabian-s** [comment]
this is now part of the code demo for CARTS:

https://github.com/compstat-lmu/lecture_i2ml/blob/dc88a4affe2e3c48ce4f73ecf2b490ec34787870/code-demos/code_demo_cart.Rmd#L46-L84
