### ISSUE TITLE
RF: aggregation pic

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#282]
in the last line we have p(yhat) in the pic.
that is not out notation

we use pi(x)

**Comment by RifatMehreen** [comment]
Editable link for the image - https://drive.google.com/file/d/1Ap4Okrcd9PAUNrzNQOE9WJ9Hh-nhuzLG/view?usp=sharing

I am not able to attach .svg or .xml here. Let me know what to do with that

**Comment by fabian-s** [comment]
thx. 
- please do check the notation on the slides in the classification chapter -- it should be $\hat\pi_1$ not $p(\hat(y))$. 
- the fraction at the bottom seems weird -- it's not 2 divided by 1, its 2 divided by 3. maybe just get rid of the fraction there and say 2 trees with \hat y = 1, 1 with \hat y = 0

also (and: apologies again for the back and forth and wasting your time): we would prefer google slides style graphs to draw.io, after all.... sorry.

**Comment by RifatMehreen** [comment]
I edited the picture again in google slides. Hope it is okay now. Let me know if anything needs to be edited.

The link: https://docs.google.com/presentation/d/1lU1qPlY-NQkvWCDrrV6PdDYkloF3eFudM9v2NFYg1rY/edit#slide=id.g60486b3cda_0_117

**Comment by fabian-s** [comment]
better, but not quite there yet.

First figure is fine, second one please do:

1. we do want $\hat\pi_1 = \tfrac{2}{3}$ in the classification explanation, please add
2. please use the 3 trees from the 1st figure here, that makes it easier to explain what's happening. 3rd tree looks wrong.
3. please use the entire width of the slide and put a vertical line between the trees and the classification explanation.

**Comment by RifatMehreen** [comment]
Edited the tree. Let me know if anything needs to be changed. 
Also, I did not construct the 1st tree. I constructed 2nd one as it was in the slide. The 1st tree was already constructed, should I still change the 2nd figure?

**Comment by fabian-s** [comment]
not quite what we discussed, is it? 

- please use the three trees from slide 1
- split the 2nd slide into three non-overlapping segments
- fix the notation for classification, its \pi_1(x) not p(\hat y).

**Comment by fabian-s** [comment]
![image](https://user-images.githubusercontent.com/998541/63873424-dde1a580-c9bf-11e9-845f-4588ddf5a259.png)

**Comment by RifatMehreen** [comment]
Edited it again. Hope it looks good

**Comment by fabian-s** [comment]
thx, 1st and 2nd page looks good. please render them into pdf and overwrite the old versions in the repo with new pdfs.
