### ISSUE TITLE
RF: OOB and varimp schematic pics

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#284]
there are STILL errors in there and the notation is not standard

we do not use M ensemble members but B
and the complete pics should be checked

**Comment by fabian-s** [comment]
![image](https://user-images.githubusercontent.com/998541/63681988-3c0f5c80-c7f7-11e9-865f-e00b8f63909f.png)

![image](https://user-images.githubusercontent.com/998541/63682078-67924700-c7f7-11e9-85ac-edb5c1dbaa38.png)

**Comment by RifatMehreen** [comment]
worked on the 1st image 
Link - https://docs.google.com/presentation/d/16gg9PqtEV_Ii_ZBw0zA9GdUIled-6OVkoqArX1ouTmo/edit?usp=sharing

**Comment by RifatMehreen** [comment]
2nd image 
Link - https://docs.google.com/presentation/d/16gg9PqtEV_Ii_ZBw0zA9GdUIled-6OVkoqArX1ouTmo/edit#slide=id.g4193e2316a_0_68

**Comment by fabian-s** [comment]
Thanks, looking much better already! 

- please use the notation from the slides for quantities like risk ($R_{emp}(f)$) - maybe use $R^{{OOB}}_{\text{emp}}$ or similar for the OOB risk
- please use OOB not oob for out-of-bag
- can you organize the slides themselves a little better by e.g. aligning graphical elements and their labels more precisely?
- please use b not i as the index for the trees, we use i for instances in the dataset.

**Comment by RifatMehreen** [comment]
I have edited the figure.
Also, do I need to edit the whole slide? I mean any specific one like **slides-forests1**? or all of them?

**Comment by fabian-s** [comment]
thx, better, but looking at this made me realize we need more/better notation.
let's do it like this:

-  on the variable importance slide, introduce the OOB risk for a tree b as
$R^{OOB}_b = \frac{1}{ | OOB_b |} \sum_{i \in OOB_b} L(y^{(i)}, \hat y^{(i)}_b)$ 
- use that notation throughout.
- please align graphical elements and their labels/annotations more precisely

![20190905_102346](https://user-images.githubusercontent.com/998541/64325153-eccfe580-cfc7-11e9-9290-1d39d07a5657.jpg)

![20190905_102353](https://user-images.githubusercontent.com/998541/64325058-c01bce00-cfc7-11e9-8f04-072c64340949.jpg)

(after drawing the graphic I also realised the difference is actually the wrong way around -- it should be risk *with* permutation - risk *without* permutation, please switch that around...)

**Comment by fabian-s** [comment]
you don't need to edit the Rnw filles for the slides, sorry, I meant the Google slides ...

**Comment by RifatMehreen** [comment]
Okay. Got it

**Comment by RifatMehreen** [comment]
Edited it

**Comment by fabian-s** [comment]
yes, almost there, thanks, this looks much better than what we had.
 
-  in both figures, please correct the hat on the y in the definition of R_00B, should not be above the "(i)"
-  in the first figure, please color multiple rows in blue in each table
-  in the second, please fix the labels on top of the tables -- the left ones should be "with permutation"

**Comment by RifatMehreen** [comment]
"in the first figure, please color multiple rows in blue in each table" Do you mean in slide 1? should I use different shades of blue ?

**Comment by fabian-s** [comment]
yes, slide 1, just to show that same row can be selected in multiple trees. same shade of blue, same as the one in the legend.
