### ISSUE TITLE
error: For learner classif.naiveBayes please install the following packages: e1071

### ISSUE THREAD

**Issue by vpolisky** [compstat-lmu/lecture_i2ml#288]
Unsure if it's ok to open issues, but I didn't know where to put it else: 

When doing comparison of LDA, QDA, and naive Bayes (day's 2 exercises), I'm getting error 

> For learner classif.naiveBayes please install the following packages: e1071

Seems, this package is missing?

**Comment by berndbischl** [comment]
> Unsure if it's ok to open issues, but I didn't know where to put it else:

thats actually the preferred way of feedback for this type of stuff

**Comment by berndbischl** [comment]
@schalkdaniel

**Comment by schalkdaniel** [comment]
Yes I have to update the app to solve this. I missed to mention e1071 so I guess it's not installed for the tutorial. :(

**Comment by schalkdaniel** [comment]
Should now be fixed
