### ISSUE TITLE
Mention ties in knn_manh_a_1

### ISSUE THREAD

**Issue by schalkdaniel** [compstat-lmu/lecture_i2ml#289]
There are ties for `k = 5`. We should give a hint to the students that this is on purpose and they should think about a solution for that.

**Comment by fabian-s** [comment]
this is now done in code demo for knn:

https://github.com/compstat-lmu/lecture_i2ml/blob/dc88a4affe2e3c48ce4f73ecf2b490ec34787870/code-demos/code_demo_knn.Rmd#L147-L149
