### ISSUE TITLE
CART: risk in splitting criteria

### ISSUE THREAD

**Issue by schalkdaniel** [compstat-lmu/lecture_i2ml#290]
The splitting finding is now done by using the risk of each node:

R(j,t) = R(N_1) + R(N_2)

I think we missed to use the weighted sum here to match the original algorithm:

R(j,t) = N_1/N * R(N_1) + N_2/N * R(N_2)

**Comment by schalkdaniel** [comment]
@berndbischl

**Comment by berndbischl** [comment]
Nein das ist richtig so wenn man das summierte Risiko nimmt und nicht das mittlere. Das steht auch so drauf den slides. 

Siehe aber die andere issue von mir dass es nicht so schlau ist nur das mittlere Risiko jetzt bei uns zu definieren am ersten Tag. 

Ich hab die Formel bei cart mit bedacht so hingeschrieben weil sie so schön einfach und intuitiv ist

**Comment by schalkdaniel** [comment]
Ja das ist mir klar, aber ich meine im original algorithmus gewichtet man die impurity ja noch immer mit der anzahl der beobachtungen im neuen node:

I = |N_1| / |N| * I(N_1) + |N_2| / |N| * I(N_2)

**Comment by schalkdaniel** [comment]
aaaaah, I see ..., es bleibt halt nur ein faktor und der is scheiß egal :+1:

**Comment by berndbischl** [comment]
naja warte, die faktoren in deiner formal kann man NICHT so einfach weglassen. 
der punkt ist:
die gewichtungsfaktoren müssen vor dem L oder dem I stehen, falls das L oder I eine "mittlere" größe berechnen. denn du verheiratest sonst (ungweichtet)  2 mittelwerte von 2 nicht-gleich-großen gruppen

aber ich wollte L hier als summe haben - damit dann eben die formel schön einfach wird.

aber leider führen wir L als mittelwert ein. deswegen hab ich auch die CART folie nochmal geschrieben: L soll seine summe sein, hier.

und dann die issue gemacht #274

**Comment by berndbischl** [comment]
bestätige dass dir das hier alles 100% klar ist, dann close

**Comment by schalkdaniel** [comment]
verstanden :+1:
