### ISSUE TITLE
LOGISTIC REGRESSION: Sign error during the introducing the logistic loss

### ISSUE THREAD

**Issue by schalkdaniel** [compstat-lmu/lecture_i2ml#294]
The problematic lines are on slide 6:

> L(y, f(x)) = −y log[π(x)] − (1 − y) log[1 − π(x)] 
>               = yθ^Tx − log[1 + exp(θ^Tx)]

In the second lines the sign is not correct, it should be:
> L(y, f(x)) = −y log[π(x)] − (1 − y) log[1 − π(x)] 
>               = -yθ^Tx + log[1 + exp(θ^Tx)]

**Comment by HeidiSeibold** [comment]
Has this been done already? @berndbischl is currently working on the slides.

**Comment by tpielok** [comment]
Can this be closed now? In the new slides, the logistic loss is only stated, but not derived.

**Comment by HeidiSeibold** [comment]
Closing this as it  is no longer relevant.
