### ISSUE TITLE
transform student comments from 2019 from the google docs into issues

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#298]

**Comment by berndbischl** [comment]
@schalkdaniel pls link docs here

**Comment by schalkdaniel** [comment]
https://drive.google.com/drive/folders/1jr043Bw_z0EJmzQWpj5SlQ7Wm4n6cx4Q?usp=sharing

**Comment by HeidiSeibold** [comment]
Can this be done by one of the student assistants?

**Comment by HeidiSeibold** [comment]
I got feedback from Daniel on this and incorporated in the new course. Closing.
