### ISSUE TITLE
renovate code demos

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#311]
document/extend/streamline

- [x] modify vignettes so links show up on website
- [x] day 1
- [x] day 2
- [x] day 3
- [x] day 4
- [x] day 5

**Comment by HeidiSeibold** [comment]
Those are almost done, right @tpielok 

Are they already done with mlr3?

**Comment by tpielok** [comment]
Yes, they are almost done.
But the transition to mlr3 has still do be done yet.

**Comment by HeidiSeibold** [comment]
What is the status of the code demos. I would use the next 4 days to prepare the lecture next week and need to know if they are final.

**Comment by tpielok** [comment]
Day 1 - 3 are done. I'm currently working on the mlr3 transition of day 4 (hopefully finishing today) 
And start afterward with the transition of day 5.

**Comment by HeidiSeibold** [comment]
Which are the code demos that we currently use? I am confused by all the files in the folder.

Can you also add a file with that info to the code demo folder? We do that for the slides as well, see e.g. https://github.com/compstat-lmu/lecture_i2ml/blob/devel/slides/evaluation/slides-order.txt

**Comment by tpielok** [comment]
We use the following rmd files:

- Day 1 
    - limo
    - knn 
    - splines 
- Day 2
   - gen_class
   - log_reg
   - cmp_class
- Day 3
   - overfitting
   - resampling
   - roc 
- Day 4 
    - cart
    - randomforest
- Day 5 
    - nested resampling
    - kaggle challenge

Yes, I will create such a file.

**Comment by HeidiSeibold** [comment]
Thanks  @tpielok that is very helpful!

When you have the time, it would also be good to update the Makefile. 

Let me know if you need anything from me or have any questions!

**Comment by fabian-s** [comment]
i did some of that this morning, plz update your devel / refactoring-w1920 branches

**Comment by fabian-s** [comment]
https://github.com/compstat-lmu/lecture_i2ml/commit/8601a4ded6a45f1550a4ba6ceb469357f983b93b
https://github.com/compstat-lmu/lecture_i2ml/commit/6819da54571646f8c6c5707403c2bedbd824908e

**Comment by HeidiSeibold** [comment]
@tpielok your example for knn is classification... Then it should probably be part of day 2, right?

**Comment by tpielok** [comment]
That's a good point. I think nearly everything one needs is explained [here](https://github.com/compstat-lmu/lecture_i2ml/blob/devel/slides-pdf/slides-regression-knn.pdf), 
but you're right formally classification has not been introduced at this point. The aim of this code demo was a gentle introduction of classification/knn without high-level concepts, s.t. it maybe could be used at the end of day 1 to teaser the next day? 
Shall we change this code demo to regression for next year?

**Comment by tpielok** [comment]
Can this be closed now?

**Comment by HeidiSeibold** [comment]
If you are happy with the code demos, I would say: yes :tada:

**Comment by tpielok** [comment]
There is always room for improvement, but AFAIK there are no mistakes in them that need to be hotfixed at the end of this iteration.
