### ISSUE TITLE
consistent bold notation for vector quantitites

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#314]
right now, risk functions etc are defined with a bold argument theta (vector)  for bold inputs x^(i), while the text and other definitions often uses non-boldface theta and x etc. 
Let's use bold notation consistently for all non-scalar quantities. 
especially apparent in the first set of slides on loss and linear regression. 

\theta -> \thetab
x -> \xv 

etc...

**Comment by berndbischl** [comment]
Shouldn't we handle this thru latex math?

**Comment by berndbischl** [comment]
Ok the problem is that people use the regular beta?

**Comment by berndbischl** [comment]
I think it is really important to have an easily visible checklist for this. Otherwise entropy will always increase very quickly

**Comment by fabian-s** [comment]
yes, we should use the commands defined for that in latex-math. this is orthogonal to the issue that our notation makes no consistent use of bold or regular symbols.  
since students typically struggle with all the linear algebra stuff, making the notation non-ambiguous and precise should be prioritized.

**Comment by berndbischl** [comment]
totally agree. i am just think about how can ensure that (after we have decided this) this is a) well visible to everyone who works on the slides b) our system helps people as much as possible to use the correct notation....

**Comment by fabian-s** [comment]
suggest to put this as a note on notation into our notation.Rnw in the first slide set after we've made sure the current set of slides complies with the practice.

**Comment by berndbischl** [comment]
@fabian-s i would like to give this to a hiwi, but i think we need to talk before and write the result down :(

**Comment by fabian-s** [comment]
AFAICT, this is now done fairly consistently in latex-math / our slides
