### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#317]
we need to think about the licensing of this material and make it explicit -- are we ok with anybody taking/modifying/using this stuff? 

I have no strong felings about this, 
something like 
https://github.com/rstudio-education/datascience-box/blob/master/LICENSE.md
would be fine for me. 

(since most of the creddit is due to @berndbischl and @christophM , this should be mostly their decision, IMO)

**Comment by fabian-s** [comment]
nvrmind, sorry, we already have one..... did we ever discuss this? just close it if we did.

**Comment by christophM** [comment]
The one we have sounds good to me: https://github.com/compstat-lmu/lecture_i2ml/blame/master/LICENCE

**Comment by berndbischl** [comment]
I am not a lawyer but CC seems OK for me?

**Comment by fabian-s** [comment]
alright then, great.
