### ISSUE TITLE
Numbering of single Rnws

### ISSUE THREAD

**Issue by schalkdaniel** [compstat-lmu/lecture_i2ml#319]
It would be nice to number the individual pdfs in each chapter

**Comment by fabian-s** [comment]
why? if we split slidesets or add aditional ones we'd need to renumber everything. 
isn't it enough to define the order of slides in the Makefile?

**Comment by schalkdaniel** [comment]
Actually yes, but if you only have the pdfs you either have to know the order or you click through. But maybe you are right and it isn't worth the effort. The 2 seconds of looking into the Makefile is ok.

**Comment by schalkdaniel** [comment]
I think we can close the issue.
