### ISSUE TITLE
install all R package dependencies via make install

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#322]
new target `make install` in top level makefile that calls an R-script that

- greps for all required packages (`grep library(`, `grep require(`) in slides, demos, etc
- checks whether they are installed (`installed.packages`)
- if not tries to install them locally

related to #261

**Comment by fabian-s** [comment]
@tpielok asigned this to you, is that something you feel you can tackle or should somebody else do that?

**Comment by tpielok** [comment]
@fabian-s should be no problem!
