### ISSUE TITLE
add slides on "density estimation" tasks

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#326]
this was removed from tasks, since we don't actually do it and it's really just a special case of regression (estimate entire conditional distribution instead of a conditional expectation/quantile)

**Comment by berndbischl** [comment]
needs to go into the ml onthology chapter

**Comment by HeidiSeibold** [comment]
See #449

**Comment by berndbischl** [comment]
i dont think we currently can cover that and i don't want to overcomplicate the intro
