### ISSUE TITLE
chapter on model complexity?

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#340]
some subchapter should really go into this
quite a bunch of work, but needed?

keep this VERY SHORT
we HAVE material in cim2 and rcourses

Model Complexity, Curse of Dim and Overfitting
Curse of Dim and Highdim Data
Overtitting
Regularisierung	
Bias Variance

TODO for BB? get some help?

**Comment by berndbischl** [comment]
we already talk about this a bit in 
- polyreg (effect of d)
- knn (effect ok)

(which is fine!)

**Comment by HeidiSeibold** [comment]
There is also a little bit in `slides-evaluation-overfitting`.
I think this is enough for i2ml. Maybe more can be done in CIM
