### ISSUE TITLE
chap-basics: check that losses are introduced properly

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#346]
Probleme:
Losses etwas technisch eingeführt. Vorallem will man hier KEINE überischt über alles losses geben
Minimierung des Losses wird gar nicht richtig gezeigt
Haben wir irgendein "Beispiel" zur Verfügung an dem wir uns langhangeln können?

**Comment by fabian-s** [comment]
seems fine to me. 

minimization is shown graphically at length in regression chapter.
we also now have extensive DIY "implement gradient descent" in code demos for day 1.
