### ISSUE TITLE
makefile: the makefiles should actually add an index number to the PDFs

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#353]
we dont want to add numbers to general folders and RNWs, but the makefile already has an order. would be nice if we could see this in the PDFs...

**Comment by berndbischl** [comment]
i dunno. that would imply that if a new subchapter is added we have to update links on the webpage.
thats doable, but maybe we dont even want that?
@fabian-s opinion?

**Comment by fabian-s** [comment]
a) 

We don't. order should be generated based on the includes at the top of the Rnw automatically, IMO.

b)

IMO, Makefiles in the future should look something like  9416f6989dc53012c0bfa9f445496305f307e7b2 -- no more SLOT1 SLOT2 SLOT3 BS...

**Comment by berndbischl** [comment]
ok this seems extra efforts and updating links is also not that great
will close this now

PS:

> order should be generated based on the includes at the top of the Rnw automatically, IMO.
i find topological sorting on this a bit overengineered....
