### ISSUE TITLE
improve regression tree picture

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#358]
instead of this:
![image](https://user-images.githubusercontent.com/998541/64618504-acfe6900-d3e0-11e9-8121-42735f7058e2.png)
(day-03/figure_man/regression_tree.pdf)

let's have something like this:
![20190910_154357](https://user-images.githubusercontent.com/998541/64619485-74f82580-d3e2-11e9-9487-35ed1be81fe6.jpg)

-  bottom part done with ggplot2, similar as now but with lots more data points and much less prominent "true" function. 
- properly label the splits in the tree diagram above.

EDIT: actually, my dreaweing above misses the value of the prediction in each leaf, that should be there as well, like in the old version.

**Comment by RifatMehreen** [comment]
Image link - https://docs.google.com/presentation/d/1Pns5UJyc-Aqyk9d-CLekA46BC7UJ_e0uSdErat47opM/edit#slide=id.p

**Comment by fabian-s** [comment]
access denied?
plz share

**Comment by RifatMehreen** [comment]
Sorry. This is the shared one - https://docs.google.com/presentation/d/1Pns5UJyc-Aqyk9d-CLekA46BC7UJ_e0uSdErat47opM/edit?usp=sharing

**Comment by fabian-s** [comment]
yeah, that's what i was looking for pretty much, thx!

- is that really a fitted tree ? heights and positions of the step seem rather sub-optimal to me...? please do use an actual fit or at least try to eyeball that a little better
- please use a different color for the points

**Comment by RifatMehreen** [comment]
Edited it

**Comment by fabian-s** [comment]
ok, thx, great! please put the code for the bottom part in the figure_man
folder with comments what this is for and URL of the slides, replace the
original figure with this, etc pp to finish this up. no rush, i'm on
vacation now anyways... have a good weekend 😊

Rifat M. Amin <notifications@github.com> schrieb am Fr., 13. Sep. 2019,
17:43:
