### ISSUE TITLE
improve bootstrapping picture

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#363]
![image](https://user-images.githubusercontent.com/998541/64845029-78212a80-d609-11e9-80b0-cdf537e1156b.png)

figure_man/04-trees/bootstrapping.png

- replace $\hat f_1$,  ..., $\hat f_3$ with our notation for baselearners $b^{[1]}, b^{[2]}$ etc

**Comment by RifatMehreen** [comment]
Link for the new image-
https://docs.google.com/presentation/d/1xodP6ayu1Gay6mMKgzVWYEFmSoeG5kNuqsaTkFFmd78/edit?usp=sharing

**Comment by fabian-s** [comment]
great, thanks! now please 
- create a new branch off the most current devel branch
-change into this branch 
- render the pdf and put it into figure_man, include it  and the URL in the slides, make sure the slides render nicely
- make a PR that includes ONLY these specific changes and no other changed files and has no conflicts with devel
