### ISSUE TITLE
Create CONTRIBUTING.md

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#385]
Sticking to common repo standards we might want a CONTRIBUTING.md

See https://help.github.com/en/articles/setting-guidelines-for-repository-contributors#adding-a-contributing-file

**Comment by berndbischl** [comment]
directly set this up? as a short version

**Comment by HeidiSeibold** [comment]
Needs to compile info / link to 

- https://github.com/compstat-lmu/lecture_i2ml/blob/devel/attic/onboarding.md
- https://github.com/compstat-lmu/lecture_i2ml/blob/master/README_intern.md

Is there a reason these two documents are seperate?

**Comment by HeidiSeibold** [comment]
Add info: https://github.com/compstat-lmu/latex-math needs to be in the same folder as this repo

**Comment by HeidiSeibold** [comment]
Recommend installing tinytex:

`tinytex::install_tinytex()`

**Comment by fabian-s** [comment]
> Needs to compile info / link to
> 
>     * https://github.com/compstat-lmu/lecture_i2ml/blob/devel/attic/onboarding.md
> 
>     * https://github.com/compstat-lmu/lecture_i2ml/blob/master/README_intern.md
> 
> 
> Is there a reason these two documents are seperate?

the latter is for *adult* collaborators, the former is about micromanaging student assistants. they should remain separate because they have different audiences, i  think.

**Comment by HeidiSeibold** [comment]
Use template:

`usethis::use_tidy_contributing`

**Comment by HeidiSeibold** [comment]
> the latter is for adult collaborators, the former is about micromanaging student assistants. they should remain separate because they have different audiences, i think.

But then the `onboarding.md` says this:


_Please read and understand the [internal README](https://github.com/compstat-lmu/lecture_i2ml/blob/master/README_intern.md) and set up your local copy of the `i2ml` repo accordingly._

**Comment by HeidiSeibold** [comment]
Add the following infos: 

- [ ]  how do i make the slides?
- [ ]  where are slides hosted?
- [ ]  how are videos recorded?
- [ ]  how are videos uploaded?
- [ ]  how is the website edited?
- [ ] how can i locally render tthe RMDs to look at them (website)

See #261

**Comment by fabian-s** [comment]
> But then the `onboarding.md` says this:
> 
> _Please read and understand the [internal README](https://github.com/compstat-lmu/lecture_i2ml/blob/master/README_intern.md) and set up your local copy of the `i2ml` repo accordingly._

yeah, well, all the info in the contributing guidelines is relevant for student assistants as well. but I still think the stuff about using git and time tracking via github projects etc is not useful in CONTRIBUTING.md

**Comment by berndbischl** [comment]
> yeah, well, all the info in the contributing guidelines is relevant for student assistants as well. but I still think the stuff about using git and time tracking via github projects etc is not useful in CONTRIBUTING.md

agreed

**Comment by berndbischl** [comment]
contributing should be general guidelines for everyone, our own stuff should be documented in a 2nd separate doc

**Comment by HeidiSeibold** [comment]
Ok, then I only think we have to make sure that it is clear this is only for students. Because currently the README.md calls it "documentation for new collaborators", but it should be "documentation for student assistants". Will add that to PR #402

**Comment by berndbischl** [comment]
@HeidiSeibold do you want to finish this so we can close. #402  is merged. 
you can also smaller issues if stuff remains unsolved here

**Comment by fabian-s** [comment]
closed in ee8d5f3. remaining open points are website-related, so move this discussion to #309
