### ISSUE TITLE
Add example: components of a learner

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#386]
Regarding

https://github.com/compstat-lmu/lecture_i2ml/blob/refactoring-w1920/slides/ml-basics/slides-basics-learnercomponents-hro.Rnw

I think it might be nice to show what the three components are in, e.g., a linear model in R.

Hypothesis space: linear combinations
Risk: mean squared error (`lm()`); negative log-likelihood (`glm()`)
Optimization: Least squares/QR factorization (`lm()`); Fisher Scoring/Iteratively Reweighted Least Square (`glm()`)

**Comment by berndbischl** [comment]
no, we dont do this. the slides are meant to be completely disentangled from R. thats important. 
the reason is that the material should be "language agnostic", and should also be combinable with python.

stuff like this has to go into demos or exercises, which are of course not language agnostic

**Comment by berndbischl** [comment]
we can leave this open, if we want to check that this is mentioned in a demo?

**Comment by HeidiSeibold** [comment]
Well, I found the concept of the three components a bit hard to grasp. 
(And if I do, probably the students do too :grimacing:)

It helped me to think about, what they mean for different methods and I thought an example would be helpful. 

It does not need to be in combination with R, I just happen to be most knowledgeable in R and what *Optimization* is, depends on the implementation in the Software.

What I envisioned was a slide like this:

---
## Example: linear regression
 (a possible implementation)

**Hypothesis space**: linear combinations
**Risk**: mean squared error
**Optimization**: Least squares/QR factorization 

---

**Comment by berndbischl** [comment]
> Well, I found the concept of the three components a bit hard to grasp.
> (And if I do, probably the students do too )

ok, thats important feedback then, and appreciated.


> It helped me to think about, what they mean for different methods and I thought an example would be helpful.

well..... the whole LM chapter is kinda there, so we go through these 3 components sloooowly, with a model which they hopefully ALREADY know, but usually taught differently.
so ideally they should learn how the 3 components look for the LM, instead of the general idea of the LM. 
if we fail at that, its a bad lecture chunk.

**Comment by fabian-s** [comment]
a slide like that is now aprt of the slideset
