### ISSUE TITLE
Make slides more neutral

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#389]
- [x] Remove LMU logo
- [x]  No names on slides (instead link to [team page](https://github.com/compstat-lmu/lecture_i2ml/blob/devel/vignettes/team.Rmd))

**Comment by fabian-s** [comment]
see also #342

**Comment by fabian-s** [comment]
this is our new miminalistic title slide layout:

![image](https://user-images.githubusercontent.com/998541/70389421-5abcec00-19bf-11ea-830e-c13f0f4dda5f.png)

closing this -- done is better than perfect. logo can come in eventually
