### ISSUE TITLE
Update team on website

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#390]
https://compstat-lmu.github.io/lecture_i2ml/articles/team.html

**Comment by fabian-s** [comment]
oh man... 

thx, should also add a remark on updating this to the file we'll create for #385

**Comment by HeidiSeibold** [comment]
> thx, should also add a remark on updating this to the file we'll create for #385

See 8ae3b80fa1a2c9580e477b7f7afa778e231d3f04
