### ISSUE TITLE
MAJOR ISSUE: we have over 100 open issues.

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#397]
well, now we have....

**Comment by berndbischl** [comment]
Thanks....

**Comment by fabian-s** [comment]
No problem, Bernd, my pleasure. I have a couple of issues to open in my mind in case we ever drop below that magic line again. This repo is  :100:!

**Comment by HeidiSeibold** [comment]
We can close this!! (for now)

:fireworks: :champagne: :tada:

**Comment by fabian-s** [comment]
I'll be back!!!! :muscle:

**Comment by fabian-s** [comment]
AAAND WE'RE BAACK! 
:muscle: :100: :muscle:
