### ISSUE TITLE
Improve figures for nested CV

### ISSUE THREAD

**Issue by giuseppec** [compstat-lmu/lecture_i2ml#398]
We have this 
https://github.com/compstat-lmu/lecture_i2ml/blob/devel/05-tuning-nested/figure_man/train_valid_test.jpg
![image](https://user-images.githubusercontent.com/4238748/68029042-a68cbf00-fcb6-11e9-9f52-21e5811cf9e2.png) figure. 
If we have the source file of the figure, we could change the colors to match the colors of the nested cross-validation figure. This probably makes it easier to see the relationship between both figures. 

Here a quick example of what I mean:
![image](https://user-images.githubusercontent.com/4238748/68029003-8c52e100-fcb6-11e9-82bd-206bcc637a1d.png)

**Comment by RifatMehreen** [comment]
@giuseppec Hello, so we already changed the image for nested resampling. I am linking the google slide link down below. And let me know what you think and what should be done. https://docs.google.com/presentation/d/1W9nPHJa39Tkzzp37ZeRsEaSZjXMdFjH-rmIpimOKZKA/edit?usp=sharing

**Comment by berndbischl** [comment]
isnt the image source linked in the Rnw source? @giuseppec should not need to post about such things here

**Comment by giuseppec** [comment]
> isnt the image source linked in the Rnw source? @giuseppec should not need to post about such things here

I didn't ask "where do I find the source file", my question was rather "can we please use the same colors in both figures to make t easier to see the relationship between both figures".

Anyway, if the nested resampling figure will be changed, this might not be relevant anymore.
@RifatMehreen: One thing I am currently missing in the new figure is that I currently don't see how it relates to hyperparameter tuning:
1) Is the example only about comparing logreg (which does not have hyperparameters) with knn? And 
2) is the knn an "auto-tuner" (i.e., a combination of knn with a tuning method to find optimal value for k)?

**Comment by fabian-s** [comment]
Rifat's figure simplifies "optimize A over \alpha" to "pick between knn (fixed k, implicitly assumed) and logreg", basically.

Nobody ever understands what we're talking about here anyway, so it might be worth it to have **both** in there:
start by slowly incrementally  building up Rifats figure to explain this in a simple setting  
then use the more general diagram you linked above to link this with hyperparameter tuning

If colors are important to you, i guess Rifat could color her diagram as well, might not be the best use of her time, though...?

**Comment by berndbischl** [comment]
> I didn't ask "where do I find the source file", my question was rather "can we please use the same colors in both figures to make t easier to see the relationship between both figures". ;)

sorry, i misread. 

> Nobody ever understands what we're talking about here anyway, 

i really disagree, i have ldctured about this 1000 times. and people do understand this. i DO AGREE that we need to make this BETTER. we need a fine-grained animation and a slower explanation. so maybe we mean the same, and i am just hung up on your wording :)
yes, this section needs to be heavily improved!

**Comment by berndbischl** [comment]
and yes, colors can be optimized later. we now need a better, step by step animation? clean issue for this?

**Comment by fabian-s** [comment]
@RifatMehreen ok, so notation here is not consistent at all with what's on the rest of the slides:
![image](https://user-images.githubusercontent.com/998541/69751025-85e94500-114e-11ea-9fb5-701d91b6b39f.png)
we're using lambda not alpha, inducer $mathcal I$ not A and Data $\mathcal D$ not D -- 
@RifatMehreen, the source for this file is in `figure_man/tuning_process.odp`, where some of these are already fixed but not all -- please:

- use a script-I for the inducer
- use $D_{train}$ instead of split S (everywhere!)

while you're at it, you could also change the colors like Giuseppe suggested, but that's very secondary, I think....

fix that in the odp-file, export the file as tuning_process.pdf, commit your changes in a new issue branch branching off the **refactor-w1920** branch (!!) and do a PR as soon as your're done, pretty please :heart:

**Comment by fabian-s** [comment]
EDIT: it might even be quicker and nicer to just use the graphical elements on the google slide for this graphic:
https://docs.google.com/presentation/d/14xwcs5zncTjFL4hIHAprjZMmyGIPqk5vs8DS32vEAvQ/edit#slide=id.g60af4020e8_0_15
![image](https://user-images.githubusercontent.com/998541/69753386-c7302380-1153-11ea-8b73-336a5994055e.png)
and rearrange them like the figure in the comment above..... your choice.

**Comment by fabian-s** [comment]
EDITEDIT: I do think actually the second option would be much nicer because then the close connection to the previous slides is much clearer.....

**Comment by RifatMehreen** [comment]
Okay. I will start working as soon as possible

**Comment by fabian-s** [comment]
@RifatMehreen nevermind about tuning_process.odp, @juliambr shared the updated version with the correct notation this morning, so you **don't need to take action rn on this**. moving the discussion about this to #417 and closing this for now.
