### ISSUE TITLE
rename "team" webpage maybe to copyright and team and link to it on the slides

### ISSUE THREAD

**Issue by berndbischl** [compstat-lmu/lecture_i2ml#404]
- [x] the webpage should outline and give credit to who worked on what (already have this)

- [x] we should briefly mention our licence and link to it

- [x] link to "contributing" and that contributors are welcome

- [ ] link to this page from each starting slide with 3 words, so that the copyright is clear if one looks at the pdfs

**Comment by HeidiSeibold** [comment]
See #409

**Comment by HeidiSeibold** [comment]
All except the starting slide is done (for wich I opened a new issue #450).
