### ISSUE TITLE
Organize lecture in Munich (March 2020)

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#406]
- [x] Define date
  1. Di 24
  2. Mi 25
  3. Fr 27
  4. Mo 30
  5. Di 31 

- [x]  Select room (find via [lsf](https://lsf.verwaltung.uni-muenchen.de/qisserver/rds?state=change&type=5&moduleParameter=raumSearch&nextdir=change&next=search.vm&subdir=raum&_form=display&clean=y&category=raum.search&function=nologgedin&navigationPosition=functions%2CsearchR&breadcrumb=searchFacilities&topitem=functions&subitem=search))

- [x] Setup Moodle: https://moodle.lmu.de/course/view.php?id=6126

- [x] Book room raumbuchung@stat.uni-muenchen.de (size, who teaches, when)
[course on lsf](https://lsf.verwaltung.uni-muenchen.de/qisserver/rds?state=verpublish&status=init&vmfile=no&publishid=786763&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung)

- [x] Send infos for homepage (see below) wwwmaster@stat.uni-muenchen.de 
```
Introduction to Machine Learning (3 ECTS)
Lecturers: Prof. Dr. Bernd Bischl, PD Dr. Fabian Scheipl, Dr. Heidi Seibold
Termin / Raum: 

Before 23.03. self study (see Moodle)

24.03. VU104
25.03. VU104
27.03. VU104
30.03. B247
31.03. B247

each day 09:30 - 17:00

Enrollment before 01.03. in Moodle
Moodle: https://moodle.lmu.de/course/view.php?id=6126
```

- [x] Notify students
   * MScDataScience2018@stat.uni-muenchen.de (=Kohorte letztes Jahr)
   * MScDataScience2019@stat.uni-muenchen.de (=neue Kohorte)
   * FB

- [ ] Select date for exam

**Comment by HeidiSeibold** [comment]
@schalkdaniel could you help me with Moodle? Could you create a copy of last year's course or show me how to do that?

**Comment by HeidiSeibold** [comment]
[this room](https://lsf.verwaltung.uni-muenchen.de/qisserver/rds?state=verpublish&status=init&vmfile=no&moduleCall=webInfo&publishConfFile=webInfoRaum&publishSubDir=raum&keep=y&raum.rgid=52451) in ERS might be good.

@berndbischl @fabian-s a room for 60 people should be fine, right?

**Comment by berndbischl** [comment]
60 should be fine

**Comment by HeidiSeibold** [comment]
Course is already booked out :eyes:
