### ISSUE TITLE
Which slide decks will be used on which day in our courses in March 2020?

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#408]
1. ml-basics, supervised-regression (optional: ml-philosophy)
2. supervised-classification
3. evaluation
4. trees, forests
5. tuning, nested-resampling

TODOs:

- [x] Check if this info is correct
- [x] Put this info on the website

**Comment by HeidiSeibold** [comment]
@berndbischl @fabian-s can you take a quick look at this and check if it is correct?

**Comment by fabian-s** [comment]
It's ml-basics & supervised-regression, (optional: ml-philosophy) on the first day.
rest seems correct.

**Comment by berndbischl** [comment]
i would call it like this (if you want headers / titles for the webpage)
1. ml-basics + regression
2. ml-basics + classification

the "philosophy" we need tp decide where to put. maybe lets make that an extra issue

**Comment by berndbischl** [comment]
and yes 3-5 are correct. MAYBE for day5 we can integrate some parctical stuff.
and we REALLY need to define how they learn the software.

**Comment by HeidiSeibold** [comment]
> i would call it like this (if you want headers / titles for the webpage)
> 
>     ml-basics + regression
>     ml-basics + classification

I am confused: how can ml-basics be on both days?

**Comment by HeidiSeibold** [comment]
> we REALLY need to define how they learn the software.

Separate issue?
