### ISSUE TITLE
make overtuning_data example reproducible

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#412]
commit d7160b1 added this data used in the final chunk of slides-nested-resampling, but not the script used to create it -- do you still have it, @juliambr?  (if so plz push directly to the rsrc folder in the refactoring-w1920 branch, preferably. if not, for shame.... :hankey:)

**Comment by fabian-s** [comment]
talking about  `overtuning_data.rds`

**Comment by juliambr** [comment]
I found the R script, pushed it into the rsrc folder in the refactoring-w1920 branch.

**Comment by fabian-s** [comment]
closed in b9c75a5a
