### ISSUE TITLE
slides-regression-knn formatting off

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#413]
This seems to be unintended @fabian-s 
![image](https://user-images.githubusercontent.com/14146757/69727970-d39c8800-1123-11ea-9a1e-c836bb589a45.png)

slides-regression-knn.pdf

**Comment by fabian-s** [comment]
yeah, sure does. feel free to just fix that kind of stuff as you go along? fixed in 79ac051
