### ISSUE TITLE
figure comparing mlrMBO with grid search is not reproducible

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#414]
![image](https://user-images.githubusercontent.com/998541/69760282-652bea00-1164-11ea-8696-2c4f78994d79.png)

this is "res1.png" on the tuning slides (good job at picking descriptive filenames, too! :+1:)
needs to be chnaged since it uses SVM terminology, there's no script to reproduce, no source given in the slides. @berndbischl, is this yours? git blame would indicate it is.

**Comment by berndbischl** [comment]
i can easily change this during the sprint, the code might be gone but it kinda easy to do with mlrMBO.
which method do we want to use? problem is, most of what we cover is that super-interesting for tuning?

**Comment by fabian-s** [comment]
CART or RF?  The latter is what I used to replace the other tuning example that was based on GBM. If you use large enough ranges for the pars, you do see *some* sensitivity there as well. 

I don't want to wait until your sprint -- I think it's very likely that you're not even going to get all of your own stuff done in time and we'll frustrate Heidi. 
I'll try to get it done with mlrMBO and ping you or Janek for advice if I get too badly stuck.

**Comment by berndbischl** [comment]
> CART or RF? The latter is what I used to replace the other tuning example that was based on GBM. If you use large enough ranges for the pars, you do see _some_ sensitivity there as well.

if that works, absolutely fine. RF probably better than CART. 

regarding waiting: pls ping me, not janek. janek is not even LMU anymore.
if the code is in the repo and we do asynchronously i can quickly help and we can get it done super quickly

**Comment by fabian-s** [comment]
![image](https://user-images.githubusercontent.com/998541/69825346-3cacfa00-120f-11ea-89f9-93314ede823c.png)
