### ISSUE TITLE
hyperband & autoML figures not reproducible

### ISSUE THREAD

**Issue by fabian-s** [compstat-lmu/lecture_i2ml#415]
05-tuning-nested/figure_man/hyperband3.png
05-tuning-nested/figure_man/automl1.png 

@juliambr, these seem to be yours. is there an outside source to reference or a script to reproduce? 
just close this if not and no copyright issues exist.

**Comment by fabian-s** [comment]
EDITED to add automl1.png

**Comment by juliambr** [comment]
hyperband3.png is from here from here: https://www.automl.org/wp-content/uploads/2019/05/AutoML_Book_Chapter1.pdf (Fig 1.3). 

For automl1.png, I do not know the source, sorry.
