### ISSUE TITLE
How to explain "algorithm evaluation"

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#427]
I find it hard to explain what the difference between "model evaluation" and "algorithm evaluation" is. 

![image](https://user-images.githubusercontent.com/14146757/70790784-0d14fa80-1d96-11ea-8072-ba5ec62c9356.png)

Can we improve this?

**Comment by fabian-s** [comment]
the first tries to answer:   
"how good is this *specific model* I've estimated (on data of this particular size/structure)?"  
the 2nd:  
"how well does my *procedure to estimate models* work (on data of this particular size/structure)?"

**Comment by berndbischl** [comment]
we still need to make this much clearer. i also think it is confusing to talk about this distinction on the first 2 slides

**Comment by berndbischl** [comment]
i think what we should say is this:

the goal of eval is: given some specific data set ( of size n), given a specific learner, with all hyperpars fixed, given a specific performance measure: what is the expected error on new data.

thats how we start. then later we can vary that theme. it is one question.

later we figure out that even that in ML is hard, and not so simple to do. beacause if you fit the model, you have no data left ---> hence the "sidestep" to evaluate the algorithm

**Comment by berndbischl** [comment]
a later variant is:
- we dont know the hyperpats and have to learn them ---> nested resampling

**Comment by HeidiSeibold** [comment]
Ok thanks, this helps a lot. :sunflower:
