### ISSUE TITLE
Upload videos to YouTube

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#455]
Upload:

- [x] Videos from @fabian-s 
- [x] Videos from @berndbischl 
- [x] Videos from @HeidiSeibold 

to YouTube.

**Comment by HeidiSeibold** [comment]
Can I start doing that already for videos of @fabian-s and myself?

- [ ] Yes from @fabian-s 
- [ ] Yes from @berndbischl

**Comment by berndbischl** [comment]
no please wait here, we can do this together at the end

**Comment by HeidiSeibold** [comment]
This is heavily blocking me on preparing the learnr tutorials (#451) and the website (#410). If I could start uploading the videos which are ready, that would help.

**Comment by berndbischl** [comment]
just put blank links in there? where is the problem?

**Comment by berndbischl** [comment]
fine, upload it now if you want, but pls do not merge the website "live" now ok?

**Comment by HeidiSeibold** [comment]
Ok :ok_hand: thanks!

**Comment by berndbischl** [comment]
sorry if i sound to "conservative", i just want to do some final checks in the end.... 
i appreciate your moving forward and dont want to stand in the way of that
