### ISSUE TITLE
k-NN versus KNN

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#457]
In the `supervised-regression` slides we use "k -NN", in `supervised-classification` we use "KNN".

I'd say we should stick to one. So far I have used "k-NN" in the exercises / tuorials.

**Comment by berndbischl** [comment]
Could you pls be so nice to directly change this in classif to become consistent?

**Comment by berndbischl** [comment]
> Is classif up-to-date from your side?

i am clean in terms of having pushed everything for now
