### ISSUE TITLE
Small mistake in video lesson 1.6 Introduction: Components of a Learner

### ISSUE THREAD

**Issue by corneliagru** [compstat-lmu/lecture_i2ml#506]
At minute 6:30 (https://youtu.be/zaB7WioK1Kw?t=390) X is called target and Y feature. Maybe adding a small comment overlay in the video helps the students to not confuse this.

**Comment by berndbischl** [comment]
could someone teach me how to do this?

**Comment by ludwig-max** [comment]
reshooted video in the meantime
