### ISSUE TITLE
Exercise sheet 2, task 3 b) is too difficult

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#511]
![image](https://user-images.githubusercontent.com/14146757/78115626-59e31680-7403-11ea-916b-fff4b64e17a2.png)

3 b) is too difficult especially because 

> Hint: Apply the same steps as we used in the lecture for the logistic regression

Is not correct. There was nothing of the sort in the videos. (I assume it used to be)

**Comment by tpielok** [comment]
Updated pdfs:

[exercise_2.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4419368/exercise_2.pdf)
[solution_2.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4419367/solution_2.pdf)
