### ISSUE TITLE
Cheatsheet names

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#520]
Cheatsheets are currently named with numbers. 

@RifatMehreen can you rename according to slide deck the refer to?

```  
ml-basics      
supervised-regression
supervised-classification  
evaluation   
trees     
forests      
tuning       
```
i.e. `CheatSheet_i2ml_supervised-regression.pdf` instead of `CheatSheet_i2ml_5.pdf` and so on. And `CheatSheet_i2ml_1.pdf` should probably be `CheatSheet_i2ml_notation.pdf`.

Thanks! :sunflower:

**Comment by RifatMehreen** [comment]
@HeidiSeibold I have renamed them 😊
