### ISSUE TITLE
Team page link broken on course home page

### ISSUE THREAD

**Issue by kiryteo** [compstat-lmu/lecture_i2ml#523]
The team page [link](https://compstat-lmu.github.io/lecture_i2ml/vignettes/team.Rmd) in the [section](https://compstat-lmu.github.io/lecture_i2ml/index.html#help-is-appreciated-and-welcome) doesn't render the team.Rmd page.

Is it supposed to direct to [this](https://compstat-lmu.github.io/lecture_i2ml/articles/team.html) page?

**Comment by HeidiSeibold** [comment]
Ah thanks! Yes, you are right!
