### ISSUE TITLE
Restructure the Repo

### ISSUE THREAD

**Issue by RifatMehreen** [compstat-lmu/lecture_i2ml#527]
1.  restructure the repo in a branch, so we move from RNW to tex files for the slides
that means you have to pull out the rcode from the slides and put them into well structured extra files in the rsrc folder

2.  do this in a branch. **do it for 1-2 chapters cleanly, and get feedback**

3.  do NOT change anything else, like contents. ensure that the external files are well named and reproducible

4.  a script should be fully reproducible, and properly save all required objects (these will in 99,9% be tables and figs) at the end on disk, under a proper name. you need to somehow make decisions how much goes into one script. please do this "intelligently"

5.  scripts shouldn't be too long. and if stuff is completely independent of each other, put it in different scripts

6.  if multiple plots all build upon each other / and or they all need the same lengthy setup code, put them in 1 script which stores multiple plots

**Comment by ludwig-max** [comment]
that's finished, right? Then please close the issue.
