### ISSUE TITLE
Link to cheatsheet "Supervised Classification" broken

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#533]
Our website https://compstat-lmu.github.io/lecture_i2ml/articles/content.html#cheat-sheets links to https://nbviewer.jupyter.org/github/compstat-lmu/lecture_i2ml/blob/master/cheatsheets/CheatSheet_i2ml_2.pdf and I get

![image](https://user-images.githubusercontent.com/14146757/93782250-9d884180-fc2a-11ea-817a-49f96a8ef5d5.png)

**Comment by ludwig-max** [comment]
if I click on the link, everything is fine..?

**Comment by berndbischl** [comment]
works for me too? browser pdf plugin problem?

**Comment by HeidiSeibold** [comment]
The other pdfs work fine, so it seems to be ok in general. I have the issue both on Chromium and Firefox.

**Comment by ludwig-max** [comment]
outdated
