### ISSUE TITLE
Content table broken

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#549]
There are suddenly NAs in this table: https://compstat-lmu.github.io/lecture_i2ml/articles/content.html

![image](https://user-images.githubusercontent.com/14146757/98255622-e0ee0380-1f7d-11eb-865f-be2ebf4271f5.png)

**Comment by berndbischl** [comment]
@ludwig-max 

this wwebsite will go offline very soon, as we are using the new version already, so i am not sure how relevant this is anymore

**Comment by HeidiSeibold** [comment]
Maybe forward the old links to the new website?

**Comment by ludwig-max** [comment]
Yes, the question is more how to take the website offline without erasing our readme here in the repo.. The title page links to the new website already and there, all videos should work
