### ISSUE TITLE
Forward from old to new website

### ISSUE THREAD

**Issue by HeidiSeibold** [compstat-lmu/lecture_i2ml#598]
The old website is kinda broken and wrong now. Can we just forward from there to the new site?

Old site: https://compstat-lmu.github.io/lecture_i2ml

**Comment by ludwig-max** [comment]
What do you mean? The first two sentences are "This Project offers a free, open source introductory and applied overview of supervised machine learning. Main course site: https://introduction-to-machine-learning.netlify.app/" Do you mean a direct forward, not a link?

**Comment by HeidiSeibold** [comment]
There is so much on this page, that I did not even see this text. So I would either directly forward the link or make it much more prominent (big red text like "new course website available: https://introduction-to-machine-learning.netlify.app."). I'd prefer the forwarding.

**Comment by ludwig-max** [comment]
I think you are right. Do you know how to do this?

**Comment by berndbischl** [comment]
just remove all the old text? and replace it with "the project moved and was updated --> please go here <NEW URL>"
?

**Comment by berndbischl** [comment]
thats easier than figuring out how we can do URL forwarding (which might be possible)
AND more transparent / less confusing?

**Comment by ludwig-max** [comment]
Yes, but the problem is that the start page is exactly the readme of the repo. So that's gone then as well.

**Comment by berndbischl** [comment]
just the remove the whole pckdown stuff? then the README is not the frontpage anymore?

**Comment by ludwig-max** [comment]
like this? https://compstat-lmu.github.io/lecture_i2ml
