### ISSUE TITLE
Regularization elastic-net figure seems wrong

### ISSUE THREAD

**Issue by ja-thomas** [compstat-lmu/lecture_i2ml#639]
![Screenshot from 2021-06-15 11-13-51](https://user-images.githubusercontent.com/7561944/122027342-5733cd80-cdcb-11eb-9e92-4cbce5a29b49.png)

vs.

![elastic-net01](https://user-images.githubusercontent.com/7561944/122027585-88ac9900-cdcb-11eb-9b51-17c740d652b9.png)

**Comment by berndbischl** [comment]
Hi kannst du bitte wenigstens etwas Kontext schreiben. Und chunk Namen. Ich verstehe aber auch inhaltlich nicht was du meinst.

Der erste Plot sieht korrekt aus. Der zweite zeigt nur l1 im label.der Plot sieht aus wie l2?

**Comment by ja-thomas** [comment]
Slideset elasticnet regularization https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides/regularization/slides-regu-enetlogreg.tex

Dort wird figure_man/elastic-net01.png eingebunden, die so wie unten aussieht um den Unterschied von L1/L2/Elastic-Net zu erklären (siehe hier: https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides/regularization/figure_man/elastic-net01.png).

Imo. müsste es aber die obere Grafik sein (oder eher obv.) die Grafik kann ich aber in der Form so weder in i2ml oder im cim2 repository finden (die obere grafik ist ein Screenshot von den Slides auf der website...)
